OxoTube/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, re_path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include(('home.urls', 'home'), namespace='home')),
    re_path('dashboard/', include(('analytics.urls', 'analytics'), namespace='analytics')),
    re_path('api/', include(('serverapi.urls', 'serverapi'), namespace='serverapi')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

handler404 = 'home.views.handler404'
handler500 = 'home.views.handler500'

analytics/urls.py
# analytics\urls.py
from django.urls import path
from .views import *

app_name = "analytics"
urlpatterns = [
    path('', dashboard_view, name='dashboardPage'),
]

home/urls.py
# home\urls.py
from django.urls import path, re_path
from .views import *

app_name = "home"
urlpatterns = [
    path('', signup_view, name='signUpPage'),
    path('login/', signin_view, name='logInPage'),
    path('video/', home_view, name='videosPage'),
    path('logout/', logout_view, name='logOutPage')
]

analytics/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import ContentType

User = settings.AUTH_USER_MODEL


class ObjectViewed(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    ip_address = models.GenericIPAddressField(max_length=220, blank=True, null=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s viewed on %s' % (self.content_object, self.timestamp)

    class Meta:
        ordering = ['-timestamp']
        verbose_name = 'Object Viewed'
        verbose_name_plural = 'Objects Viewed'

analytics/forms.py
from django import forms
from django.forms import ModelForm
from home.models import VideoItem
from embed_video.fields import EmbedVideoFormField


class VideoAddForm(ModelForm):
    url = EmbedVideoFormField()

    class Meta:
        model = VideoItem
        fields = ('url',)

analytics/views.py
from django.http import JsonResponse
from django.shortcuts import render
from home.models import VideoItem
from .forms import VideoAddForm
from django.contrib.admin.views.decorators import staff_member_required


@staff_member_required()
def dashboard_view(request):
    form = VideoAddForm()
    if request.method == 'POST':
        video_add_form = VideoAddForm(request.POST)
        if video_add_form.is_valid():
            try:
                VideoItem.objects.get(url=video_add_form.cleaned_data['url'])
                print('Video Already Embedded')
            except VideoItem.DoesNotExist:
                video_add_form.save()
                print('Video Added Successfully')
        else:
            print('invalid form')
    context = {'video_add_form': form}
    return render(request, 'analytics/dashboard.html', context)



analytics/templates/analytics/dashboard.html
{% extends 'analytics/dashboardBase.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow">
                <div class="card-body">
                    <h6>I wasn't able to count the views of youtube, but below charts and tables data is fetched from server api, and login/signup/logout and video addition is working</h6>
                </div>
                <div class="card-body">
                    <canvas id="myChart" width="200" height="200"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="card shadow mt-3">
    <div class="card-header">
        <h6>Currently registered users</h6>
    </div>
        <div class="card-body overflow-auto">
            <table class="table" id="usertable">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">First name</th>
                      <th scope="col">Last name</th>
                      <th scope="col">Email</th>
                      <th scope="col">Active</th>
                      <th scope="row">Superuser</th>
                      <th scope="row">Staff</th>
                      <th scope="row">Joined date</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
        </div>
    </div>
    <div class="card shadow mt-3">
    <div class="card-header">
        <h6>Currently embedded videos</h6>
    </div>
        <div class="card-body overflow-auto">
            <table class="table" id="embedvideos">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">TimeStamp</th>
                      <th scope="col">URL</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
        </div>
    </div>



{% endblock %}

{% block js %}
    <script type="text/javascript" rel="script" src="{% static 'js/data.js' %}"></script>
{% endblock %}

analytics/templates/analytics/dashboardBase.html
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin Dashboard</title>
    <style>#loader {
        transition: all .3s ease-in-out;
        opacity: 1;
        visibility: visible;
        position: fixed;
        height: 100vh;
        width: 100%;
        background: #fff;
        z-index: 90000
    }

    #loader.fadeOut {
        opacity: 0;
        visibility: hidden
    }

    .spinner {
        width: 40px;
        height: 40px;
        position: absolute;
        top: calc(50% - 20px);
        left: calc(50% - 20px);
        background-color: #333;
        border-radius: 100%;
        -webkit-animation: sk-scaleout 1s infinite ease-in-out;
        animation: sk-scaleout 1s infinite ease-in-out
    }

    @-webkit-keyframes sk-scaleout {
        0% {
            -webkit-transform: scale(0)
        }
        100% {
            -webkit-transform: scale(1);
            opacity: 0
        }
    }

    @keyframes sk-scaleout {
        0% {
            -webkit-transform: scale(0);
            transform: scale(0)
        }
        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
            opacity: 0
        }
    }</style>
    <link rel="icon" href="{% static 'images/video-play-32.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
    <link type="text/css" rel="stylesheet" href="{% static 'css/dashboard.css' %}">


    {% block css %}

    {% endblock %}
    <script type="text/javascript">
        let user = '{{ request.user }}'
        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>
</head>
<body class="hero-anime">
<div id="loader">
    <div class="spinner"></div>
</div>
<script>window.addEventListener('load', function load() {
    const loader = document.getElementById('loader');
    setTimeout(function () {
        loader.classList.add('fadeOut');
    }, 300);
});
</script>
<!-- Heading -->
<div class="navigation-wrap bg-light start-header start-style">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-md navbar-light">

                    <a class="navbar-brand" href="{% url 'home:videosPage' %}"><img
                            src="{% static 'images/video-play-512.png' %}" alt=""></a>
                    <div>
                        <a href="{% url 'home:videosPage' %}" class="no-decorate"><H3 class="pt-2">OxoTube</H3></a>
                    </div>

                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto py-4 py-md-0">
                            <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                                   aria-haspopup="true" aria-expanded="false">Home</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                </div>
                            </li>
                            <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                <a class="nav-link" href="#" data-toggle="modal" data-target="#VideoAddModal">Add a
                                    Video</a>
                            </li>
                            {% if request.user.is_admin %}
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                                    <a class="nav-link" href="{% url 'analytics:dashboardPage' %}">Dashboard</a>
                                </li>
                            {% endif %}
                            <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                                   aria-haspopup="true" aria-expanded="false">Profile</a>
                                <div class="dropdown-menu">
                                    <p class="dropdown-item">Logged In as {{ request.user }}</p>
                                    <a class="dropdown-item" href="{% url 'home:logOutPage' %}">Log Out</a>
                                </div>
                            </li>
                            <li class="pl-4 pl-md-0 ml-0 ml-md-4">
                                <div>
                                    <input type="checkbox" class="checkbox" id="chk"/>
                                    <label class="label" for="chk">
                                        <i class="fas fa-moon"></i>
                                        <i class="fas fa-sun"></i>
                                        <span class="ball"></span>
                                    </label>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</div>

<!-- video add modal -->
<div class="modal fade" tabindex="-1" id="VideoAddModal" aria-labelledby="VideoAddModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Paste link of YouTube/Vimeo video</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="block-register" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    {{ video_add_form.url | as_crispy_field }}
                </div>
                <div class="modal-footer">
                    <button type="submit" value="video" class="btn btn-primary">Embed</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="container pb-5" style="top: 100px;position: relative">
    <div class="row mb-5">
            <div class="col-md-12">
                <h1 style="text-align: left;">
                    <span>S</span><span>t</span><span>a</span><span>t</span><span>s</span></h1>
                <p class="text-left">Get a bird eye view of your viewers</p>
            </div>
    </div>
{% block content %}

{% endblock %}
</div>

</body>
<script
  src="https://code.jquery.com/jquery-3.5.1.js"
  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
<script type="text/javascript" rel="script" src="{% static 'js/dashboardBase.js' %}"></script>
{% block js %}


{% endblock %}
</html>